# Generated by Django 3.1.5 on 2021-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_account',
            name='money',
        ),
        migrations.AddField(
            model_name='admin_account',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
