# Generated by Django 3.1.5 on 2021-02-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_repair_history',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='user_repair_history',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='user_history',
        ),
        migrations.DeleteModel(
            name='user_repair_history',
        ),
    ]
