# Generated by Django 3.1.5 on 2021-02-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_history', '0003_user_history_user_repair_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_repair_history',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='user_repair_history',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='user_history',
        ),
        migrations.DeleteModel(
            name='user_repair_history',
        ),
    ]
