# Generated by Django 3.1.5 on 2021-02-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_login', '0002_auto_20210201_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_account',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
