# Generated by Django 3.1.5 on 2021-02-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('u_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('money', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_login.user_account')),
            ],
        ),
    ]
