# Generated by Django 3.1.5 on 2021-02-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_rent_bike', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_route',
        ),
    ]
