# Generated by Django 3.1.5 on 2021-02-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('u_login', '0002_auto_20210208_1314'),
        ('a_manage_bike', '0001_initial'),
        ('u_rent_bike', '0002_delete_user_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(default='latitude', max_length=50)),
                ('longitude', models.CharField(default='longitude', max_length=50)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_manage_bike.bike')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_login.user_account')),
            ],
        ),
    ]
