# Generated by Django 3.1.5 on 2021-02-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_rent_bike', '0003_user_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_route',
        ),
    ]
