# Generated by Django 3.1.5 on 2021-02-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_rent_bike', '0006_auto_20210219_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_route',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_route',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
