# Generated by Django 3.1.5 on 2021-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_rent_bike', '0007_auto_20210219_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_route',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user_route',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
