# Generated by Django 3.1.5 on 2021-02-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_rent_bike', '0008_auto_20210219_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_route',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user_route',
            name='ratings',
            field=models.CharField(default='longitude', max_length=50),
        ),
    ]
