# Generated by Django 3.1.5 on 2021-02-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_rent_bike', '0009_auto_20210219_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_route',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_route',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_route',
            name='ratings',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
