# Generated by Django 3.1.5 on 2021-02-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_manage_bike', '0001_initial'),
        ('o_login', '0001_initial'),
        ('u_login', '0002_auto_20210208_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator_route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=50, null=True)),
                ('lng', models.CharField(max_length=50, null=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_manage_bike.bike')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_login.user_account')),
            ],
        ),
        migrations.CreateModel(
            name='operator_repair_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=500, null=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField()),
                ('image1', models.CharField(max_length=200, null=True)),
                ('image2', models.CharField(max_length=200, null=True)),
                ('image3', models.CharField(max_length=200, null=True)),
                ('image4', models.CharField(max_length=200, null=True)),
                ('image5', models.CharField(max_length=200, null=True)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_manage_bike.bike')),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_login.operator_account')),
            ],
        ),
    ]
