# Generated by Django 3.1.5 on 2021-02-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_manage_bike', '0005_operator_repair_history_operator_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator_repair_history',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='operator_repair_history',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
