# Generated by Django 3.1.5 on 2021-02-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_manage_bike', '0011_auto_20210219_2207'),
        ('a_manage_location', '0001_initial'),
        ('o_login', '0001_initial'),
        ('o_manage_bike', '0006_auto_20210220_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator_transport_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_manage_bike.bike')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_manage_location.location')),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_login.operator_account')),
            ],
        ),
        migrations.DeleteModel(
            name='operator_route',
        ),
    ]
