# Generated by Django 3.1.5 on 2021-02-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_bike_history', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='operator_port_history',
        ),
    ]
