# Generated by Django 3.1.5 on 2021-02-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o_bike_history', '0003_operator_port_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='operator_port_history',
        ),
    ]
