# Generated by Django 3.1.5 on 2021-02-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, null=True)),
                ('rent_money', models.FloatField()),
                ('image', models.CharField(max_length=200, null=True)),
                ('open_password', models.CharField(max_length=10, null=True)),
                ('original_lat', models.CharField(max_length=50, null=True)),
                ('original_lng', models.CharField(max_length=50, null=True)),
                ('new_lat', models.CharField(max_length=50, null=True)),
                ('new_lng', models.CharField(max_length=50, null=True)),
                ('is_use', models.BooleanField(default=False)),
            ],
        ),
    ]
