# Generated by Django 3.1.5 on 2021-02-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('u_login', '0002_auto_20210208_1314'),
        ('o_login', '0001_initial'),
        ('a_manage_bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bike_route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=50, null=True)),
                ('lng', models.CharField(max_length=50, null=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_manage_bike.bike')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_login.user_account')),
            ],
        ),
        migrations.CreateModel(
            name='bike_malfunction_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField()),
                ('is_repaired', models.BooleanField(default=False)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_manage_bike.bike')),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_login.operator_account')),
            ],
        ),
    ]
