# Generated by Django 3.1.5 on 2021-02-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_manage_bike', '0005_bike_malfunction_history_bike_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bike_route',
        ),
    ]
