# Generated by Django 3.1.5 on 2021-02-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_manage_bike', '0006_delete_bike_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_malfunction_history',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
