# Generated by Django 3.1.5 on 2021-02-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_manage_bike', '0007_auto_20210219_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='is_use',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
