# Generated by Django 3.1.5 on 2021-02-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_manage_bike', '0008_auto_20210219_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_malfunction_history',
            name='detail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bike_malfunction_history',
            name='image1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bike_malfunction_history',
            name='image2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bike_malfunction_history',
            name='image3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bike_malfunction_history',
            name='image4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bike_malfunction_history',
            name='image5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bike_malfunction_history',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike_malfunction_history',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike_malfunction_history',
            name='question_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
