# Generated by Django 3.1.5 on 2021-02-19 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o_login', '0001_initial'),
        ('a_manage_bike', '0009_auto_20210219_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_malfunction_history',
            name='operator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='o_login.operator_account'),
        ),
    ]
