# Generated by Django 3.1.5 on 2021-02-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_manage_bike', '0010_auto_20210219_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_malfunction_history',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bike_malfunction_history',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
