# Generated by Django 3.1.5 on 2021-01-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('money', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
