# Generated by Django 3.1.5 on 2021-02-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_login', '0002_auto_20210208_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='payPassword',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
