# Generated by Django 3.1.5 on 2021-02-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a_test',
        ),
    ]
