# Generated by Django 3.1.5 on 2021-02-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('u_login', '0003_user_account_paypassword'),
        ('a_manage_bike', '0006_delete_bike_route'),
        ('u_rent_bike', '0005_user_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='bike_route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=50, null=True)),
                ('lng', models.CharField(max_length=50, null=True)),
                ('time', models.TimeField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_manage_bike.bike')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_login.user_account')),
                ('user_rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_rent_bike.user_route')),
            ],
        ),
    ]
