# Generated by Django 3.1.5 on 2021-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_biking', '0002_auto_20210219_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_route',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
